MIN_CONTOUR_AREA_FRACTION = 0.01

# ECC fine alignment parameters
ECC_MAX_ITERATIONS = 50
ECC_EPSILON        = 1e-4
ECC_WARP_MODE      = 1   # cv2.MOTION_EUCLIDEAN = 1  (NOT 3 which is MOTION_HOMOGRAPHY)

# Legacy ORB constants — kept so existing tests that import them don't break
ORB_N_FEATURES = 1000
ORB_SCALE_FACTOR = 1.2
ORB_N_LEVELS = 8

MIN_MATCH_COUNT = 8
RANSAC_REPROJ_THRESHOLD = 3.0
MIN_INLIER_RATIO = 0.35   # raised from 0.10

SCALE_MIN = 0.5
SCALE_MAX = 2.0

HIGH_CONFIDENCE_THRESHOLD = 0.80
COVERAGE_THRESHOLD = 0.85
